FROM node:18
WORKDIR /app
COPY ./webhook/package.json /app/webhook/
COPY ./webhook/src /app/webhook/src/
COPY ./webhook/tsconfig.json /app/webhook/
COPY ./webhook/nodemon.json /app/webhook/
WORKDIR /app/webhook
RUN npm install
RUN npm run build
EXPOSE 8000
CMD [ "npm", "run", "start" ]